# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: rumdl-check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-inlined-logs:
    runs-on: windows-2022
    steps:
      - name: Project Checkout
        uses: actions/checkout@v6.0.0

      - name: Lint with rumdl
        uses: ubiratansoares/rumdl@ufs/rumdl-action
        with:
          report-type: workflow-logs

  lint-workflow-annotations:
    runs-on: macos-15
    steps:
      - name: Project Checkout
        uses: actions/checkout@v6.0.0

      - name: Lint with rumdl
        uses: ubiratansoares/rumdl@ufs/rumdl-action
        with:
          report-type: workflow-annotations

  lint-invalid-report:
    runs-on: macos-15
    steps:
      - name: Project Checkout
        uses: actions/checkout@v6.0.0

      - name: Lint with rumdl
        uses: ubiratansoares/rumdl@ufs/rumdl-action
        with:
          report-type: sarif
